extends SceneTree
## Native OS input observer. No Main, collection, preferences, or synthetic
## events exist here. The human is asked to press printed Nintendo A then B.
const Bindings = preload("res://scripts/controller_bindings.gd")
const FrontEnd = preload("res://scripts/front_end.gd")
class NativeObserver extends Node:
	signal native_input(event: InputEvent)
	func _input(event: InputEvent) -> void: native_input.emit(event)
var output: String = ""
var ready_path: String = ""
var events: Array = []
var devices: Array = []
var printed_a: Dictionary = {}
var printed_b: Dictionary = {}
var start_ticks: int = 0
var title_label: Label
var event_label: Label
var status_label: Label
var finished: bool = false
var remaining: int = 0
var cancelled: bool = false
var self_check: bool = false
func _initialize() -> void: call_deferred("run")
func label(text: String, area: Rect2, size: int = 20) -> Label:
	var item := Label.new(); item.text = text; item.position = area.position; item.size = area.size
	item.add_theme_font_override("font",FrontEnd.pixel_font()); item.add_theme_font_size_override("font_size",size)
	item.add_theme_color_override("font_color",Color("e3e8dc")); item.mouse_filter = Control.MOUSE_FILTER_IGNORE
	root.add_child(item); return item
func run() -> void:
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--report="): output = arg.trim_prefix("--report=")
		if arg.begins_with("--ready="): ready_path = arg.trim_prefix("--ready=")
		if arg == "--self-check": self_check = true
	assert(output.is_absolute_path() and ready_path.is_absolute_path() and not FileAccess.file_exists(output) and not FileAccess.file_exists(ready_path))
	root.size = Vector2i(640,360); root.content_scale_size = Vector2i(640,360)
	auto_accept_quit = false
	root.close_requested.connect(func() -> void: cancelled = true; finished = true; remaining = 1)
	var observer := NativeObserver.new(); root.add_child(observer); observer.native_input.connect(observe_native_input)
	DisplayServer.window_set_title("Spinning Metal — Nintendo physical controller check")
	Bindings.configure("nintendo")
	start_ticks = Time.get_ticks_msec()
	var background := ColorRect.new(); background.color = Color("10151f"); background.size = Vector2(640,360); background.mouse_filter = Control.MOUSE_FILTER_IGNORE; root.add_child(background)
	label("NINTENDO PHYSICAL BUTTON CHECK",Rect2(20,20,600,30))
	label("Controller type: NINTENDO / No player save is opened",Rect2(20,56,600,22),10)
	title_label = label("PRESS PRINTED A",Rect2(20,104,600,35),30)
	label("Then release A and press the printed B button.",Rect2(20,147,600,24),10)
	event_label = label("Waiting for native controller input...",Rect2(20,189,600,54),10)
	status_label = label("No synthetic input is generated by this observer.",Rect2(20,300,600,42),10)
	for device: int in Input.get_connected_joypads():
		devices.append({"device":device,"mapped_name":Input.get_joy_name(device),"guid":Input.get_joy_guid(device),"info":Input.get_joy_info(device),"known":Input.is_joy_known(device),"auto_profile":FrontEnd.controller_profile(device),"selected_profile":Bindings.profile(device)})
	if not devices.is_empty(): label(str(devices[0].mapped_name) + " / " + str(devices[0].guid),Rect2(20,260,600,27),10)
	var file := FileAccess.open(ready_path,FileAccess.WRITE); file.store_string(JSON.stringify({"ready":true,"pid":OS.get_process_id(),"devices":devices,"instructions":"Press printed A, release, then press printed B. This window only observes native OS events."},"\t")); file.close()
	print("PHYSICAL_CONTROLLER_PROBE_READY ", ready_path)
	if self_check: finished = true; remaining = 1
	while Time.get_ticks_msec() - start_ticks < 180000:
		await process_frame
		if finished:
			remaining -= 1
			if remaining <= 0: break
	var result: Dictionary = {"scope":"Native Godot OS-input observer. Human declaration assigns first printed A then printed B; physical labelling must be confirmed by the human. No synthetic events, Main, or player profile are used.","devices":devices,"events":events,"printed_a":printed_a,"printed_b":printed_b,"cancelled":cancelled,"self_check":self_check,
		"both_received":not printed_a.is_empty() and not printed_b.is_empty(),"selected_layout":"nintendo","elapsed_seconds":float(Time.get_ticks_msec()-start_ticks)/1000.0,
		"mapping_matches":not printed_a.is_empty() and not printed_b.is_empty() and bool(printed_a.ui_accept) and not bool(printed_a.ui_cancel) and bool(printed_b.ui_cancel) and not bool(printed_b.ui_accept)}
	var report := FileAccess.open(output,FileAccess.WRITE); report.store_string(JSON.stringify(result,"\t")); report.close()
	print("PHYSICAL_CONTROLLER_PROBE_RESULT ", JSON.stringify(result))
	quit()
func observe_native_input(event: InputEvent) -> void:
	if not event is InputEventJoypadButton or finished: return
	var row: Dictionary = {"elapsed_msec":Time.get_ticks_msec()-start_ticks,"frame":Engine.get_process_frames(),"device":event.device,"button_index":event.button_index,"pressed":event.pressed,
		"ui_accept":event.is_action("ui_accept"),"ui_cancel":event.is_action("ui_cancel"),"event_text":event.as_text()}
	events.append(row)
	print("PHYSICAL_CONTROLLER_EVENT ", JSON.stringify(row))
	if not event.pressed or event.button_index not in [JOY_BUTTON_A,JOY_BUTTON_B]: return
	if printed_a.is_empty():
		printed_a = row.duplicate(true)
		title_label.text = "NOW PRESS PRINTED B"
		event_label.text = "PRINTED A -> Godot logical button %d\nConfirm=%s / Back=%s" % [event.button_index,event.is_action("ui_accept"),event.is_action("ui_cancel")]
	elif printed_b.is_empty():
		printed_b = row.duplicate(true)
		title_label.text = "BOTH BUTTONS RECEIVED"
		event_label.text += "\nPRINTED B -> Godot logical button %d / Confirm=%s / Back=%s" % [event.button_index,event.is_action("ui_accept"),event.is_action("ui_cancel")]
		status_label.text = "Recorded native events. Returning to the task in three seconds."
		finished = true; remaining = 180
